### ISSUE TITLE
Password reset accepts unregistered email 

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-authn-password#11]
If you use the password reset function and enter an unregistered email address, it claims that an email was sent to the address when one wasn't (and the console prints an error indicating that the email was not registered). Instead, the UI should indicate that the email address is not registered.

**Comment by mattcollier** [comment]
This was by design to prevent an attacker from discovering the existence of an account.  If you don't care for that approach, we can return an error to the user if the account does not exist.

**Comment by dlongley** [comment]
Yeah, I think it will be more frustrating for users than it will be privacy protecting.
